# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qWPyGQ9I3o-bJh_eQ0z8IIY6lHGTOhLV
"""

import pandas as pd
import matplotlib.pyplot as plt


url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv"


df = pd.read_csv(url)


print(df.head())


df.to_csv("cars_data.csv", index=False)

df_clean = df.dropna()

avg_mpg = df_clean.groupby("cylinders")["mpg"].mean()


plt.figure(figsize=(8,5))
avg_mpg.plot(kind="bar")
plt.title("Average MPG by Number of Cylinders")
plt.xlabel("Cylinders")
plt.ylabel("Miles Per Gallon (MPG)")
plt.tight_layout()
plt.show()